//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTest {
    
    
    public class TestScopeOfflineEntityBase : object, Microsoft.Synchronization.ClientServices.IOfflineEntity {
        
        private Microsoft.Synchronization.ClientServices.OfflineEntityMetadata _serviceMetadata;
        
        public TestScopeOfflineEntityBase() {
            ServiceMetadata = new Microsoft.Synchronization.ClientServices.OfflineEntityMetadata();
        }
        
        public virtual Microsoft.Synchronization.ClientServices.OfflineEntityMetadata ServiceMetadata {
            get {
                return _serviceMetadata;
            }
            set {
                if ((value == null)) {
                    throw new System.ArgumentNullException("value");
                }
                _serviceMetadata = value;
            }
        }
    }
    
    public partial class Table : TestScopeOfflineEntityBase {
        
        private int _Id;
        
        private string _Name;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int Id {
            get {
                return _Id;
            }
            set {
                _Id = value;
            }
        }
        
        public string Name {
            get {
                return _Name;
            }
            set {
                _Name = value;
            }
        }
    }
    
    public partial class ChildTable : TestScopeOfflineEntityBase {
        
        private int _Id;
        
        private int _TableId;
        
        private string _Name;
        
        [System.ComponentModel.DataAnnotations.KeyAttribute()]
        public int Id {
            get {
                return _Id;
            }
            set {
                _Id = value;
            }
        }
        
        public int TableId {
            get {
                return _TableId;
            }
            set {
                _TableId = value;
            }
        }
        
        public string Name {
            get {
                return _Name;
            }
            set {
                _Name = value;
            }
        }
    }
}
