//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTest {
    
    
    public class TestScopeOfflineEntityBase : object, Microsoft.Synchronization.Services.IOfflineEntity {
        
        private Microsoft.Synchronization.Services.OfflineEntityMetadata _serviceMetadata;
        
        public TestScopeOfflineEntityBase() {
            ServiceMetadata = new Microsoft.Synchronization.Services.OfflineEntityMetadata();
        }
        
        public virtual Microsoft.Synchronization.Services.OfflineEntityMetadata ServiceMetadata {
            get {
                return _serviceMetadata;
            }
            set {
                if ((value == null)) {
                    throw new System.ArgumentNullException("value");
                }
                _serviceMetadata = value;
            }
        }
    }
    
    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName="Table", TableLocalName="[Table]", KeyFields="Id")]
    public partial class Table : TestScopeOfflineEntityBase {
        
        private int _Id;
        
        private string _Name;
        
        public int Id {
            get {
                return _Id;
            }
            set {
                _Id = value;
            }
        }
        
        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Name {
            get {
                return _Name;
            }
            set {
                _Name = value;
            }
        }
    }
    
    [Microsoft.Synchronization.Services.SyncEntityTypeAttribute(TableGlobalName="ChildTable", TableLocalName="[ChildTable]", KeyFields="Id")]
    public partial class ChildTable : TestScopeOfflineEntityBase {
        
        private int _Id;
        
        private int _TableId;
        
        private string _Name;
        
        public int Id {
            get {
                return _Id;
            }
            set {
                _Id = value;
            }
        }
        
        public int TableId {
            get {
                return _TableId;
            }
            set {
                _TableId = value;
            }
        }
        
        [Microsoft.Synchronization.Services.SyncEntityPropertyIsNullableAttribute()]
        public string Name {
            get {
                return _Name;
            }
            set {
                _Name = value;
            }
        }
    }
    
    [Microsoft.Synchronization.Services.SyncScopeAttribute()]
    public class TestScopeOfflineEntities {
        
        private System.Collections.Generic.ICollection<Table> _Tables;
        
        private System.Collections.Generic.ICollection<ChildTable> _ChildTables;
    }
}
