//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTest {
    
    
    #region SyncService: Configuration and setup
    public class TestScopeSyncService : Microsoft.Synchronization.Services.SyncService<TestScopeOfflineEntities> {
        
        public static void InitializeService(Microsoft.Synchronization.Services.ISyncServiceConfiguration config) {
            // TODO: MUST set these values
             config.ServerConnectionString = "Data Source=(localdb)\\ProjectsV13;Initial Catalog=SyncTest;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
             config.SetEnableScope("TestScope");
            // 
            // 
            // TODO: Optional.
             config.SetDefaultSyncSerializationFormat(Microsoft.Synchronization.Services.SyncSerializationFormat.ODataJson);
             config.SetConflictResolutionPolicy(Microsoft.Synchronization.Services.ConflictResolutionPolicy.ServerWins);
        }
    }
    #endregion
}
