//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8689
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncTest {
    
    
    #region SyncService: Configuration and setup
    public class TestScopeSyncService : Microsoft.Synchronization.Services.SyncService<TestScopeOfflineEntities> {
        
        public static void InitializeService(Microsoft.Synchronization.Services.ISyncServiceConfiguration config) {
            // TODO: MUST set these values
            // config.ServerConnectionString = "connection string here";
            // config.SetEnableScope("scope name goes here");
            // 
            // 
            // TODO: Optional.
            // config.SetDefaultSyncSerializationFormat(Microsoft.Synchronization.Services.SyncSerializationFormat.ODataJson);
            // config.SetConflictResolutionPolicy(Microsoft.Synchronization.Services.ConflictResolutionPolicy.ServerWins);
        }
    }
    #endregion
}
